# Generated by Django 4.2 on 2024-08-08 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titulo")),
                ("lead", models.TextField(verbose_name="Entrada")),
                ("content", models.TextField(verbose_name="Contenido")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="post", verbose_name="Imagen"
                    ),
                ),
                (
                    "published",
                    models.BooleanField(default=False, verbose_name="Publicado"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
                (
                    "categoty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.category",
                        verbose_name="Categoria",
                    ),
                ),
                ("tag", models.ManyToManyField(to="core.tag", verbose_name="Etiqueta")),
            ],
            options={
                "verbose_name": "Publicacion",
                "verbose_name_plural": "Publicaciones",
                "ordering": ["-created"],
            },
        ),
    ]
