# Generated by Django 4.2 on 2024-08-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("desciption", models.TextField(verbose_name="Descripcion")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Acerca de",
                "verbose_name_plural": "Acerca de nosotros",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, verbose_name="Key link")),
                ("name", models.CharField(max_length=100, verbose_name="Key link")),
                (
                    "url",
                    models.URLField(
                        blank=True, max_length=250, null=True, verbose_name="Enlace"
                    ),
                ),
                ("icon", models.CharField(max_length=150, verbose_name="Icono")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Red socila",
                "verbose_name_plural": "Redes sociales",
                "ordering": ["name"],
            },
        ),
    ]
