# Generated by Django 4.2 on 2024-08-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_about_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="icon",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Icono"
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Red social"),
        ),
    ]
