# Generated by Django 4.2 on 2024-08-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_link_icon_alter_link_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="tag",
            new_name="tags",
        ),
        migrations.AlterField(
            model_name="link",
            name="key",
            field=models.CharField(max_length=100, verbose_name="Clave"),
        ),
    ]
